os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="Boost/1.60.0"
    - CONAN_USERNAME="lasote"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=8
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
       
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=5 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=7 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=8 CONAN_USE_DOCKER=1

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
